version: "3"

services:
    front:
        build: ./frontend
        image: restapi-frontend
        container_name: webpage
        ports:
            - 4000:5000
    server:
        build: ./backend
        image: restapi-backend
        container_name: server
        ports:
            - 4001:3000
