version: "3"

services:
    front:
        image: mrgk21/rest-api:frontend-v1.0.0
        container_name: webpage
        ports:
            - 5000:5000
    server:
        image: mrgk21/rest-api:backend-v1.0.0
        container_name: server
        ports:
            - 5001:5001
