version: "3"

services:
    server:
        build:
            context: ./reverse_proxy
        container_name: reverse_proxy
        ports:
            - 80:80
    backend:
        image: mrgk21/rest-api:backend-v1.0.0
        container_name: backend
        ports:
            - 5001:5001
